self.AgentErrorCodes = Object.freeze({
  TARGET_NOT_FOUND: "AGENT_TARGET_NOT_FOUND",
  PROVIDER_TIMEOUT: "AGENT_PROVIDER_TIMEOUT",
  PROVIDER_AUTH: "AGENT_PROVIDER_AUTH",
  PROVIDER_RATE_LIMIT: "AGENT_PROVIDER_RATE_LIMIT",
  INVALID_ACTION: "AGENT_INVALID_ACTION",
  SUBMIT_BLOCKED: "AGENT_SUBMIT_BLOCKED",
  SUBMIT_UNVERIFIED: "AGENT_SUBMIT_UNVERIFIED",
  PERMISSION_DENIED: "AGENT_PERMISSION_DENIED",
  IFRAME_UNAVAILABLE: "AGENT_IFRAME_UNAVAILABLE",
  DOM_CHANGED: "AGENT_DOM_CHANGED",
});
