module.exports = [
  {
    ignores: ["node_modules/**"],
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        chrome: "readonly",
        self: "readonly",
        document: "readonly",
        window: "readonly",
        location: "readonly",
        fetch: "readonly",
        crypto: "readonly",
        URL: "readonly",
        Blob: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        module: "readonly",
        require: "readonly",
        process: "readonly",
        __dirname: "readonly",
        importScripts: "readonly",
        HostUtils: "readonly",
        ActionSchema: "readonly",
        StorageManager: "readonly",
        AnswerMemory: "readonly",
        RunStateManager: "readonly",
        AgentErrorCodes: "readonly",
        resolveProfileFields: "readonly",
        parseJobContext: "readonly",
        callModel: "readonly",
        isLikelySubmitAction: "readonly",
        Element: "readonly",
        Event: "readonly",
        InputEvent: "readonly",
        KeyboardEvent: "readonly",
        PointerEvent: "readonly",
        MouseEvent: "readonly",
        MutationObserver: "readonly",
        CSS: "readonly",
        queueMicrotask: "readonly",
        computeLabel: "readonly",
        labelFor: "readonly",
        hasUploadedFile: "readonly",
        isVisible: "readonly",
        describedByText: "readonly",
        smartAutofill: "readonly",
        supportsNativeVisibilityCheck: "readonly",
        FILLED_ATTR: "readonly",
        setNativeValue: "readonly",
        agentWriteInProgress: "readonly",
        getPageSnapshot: "readonly",
        runSingleAction: "readonly",
        getFormStatus: "readonly",
      },
    },
    rules: { "no-undef": "warn", "no-unreachable": "error", "no-constant-binary-expression": "error" },
  },
];
